/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bermudatechsystem;

/**
 *
 * @author Nathan Cabral
 */
public class NewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewEmployeeID = new javax.swing.JLabel();
        lblNewEmployeeTitle = new javax.swing.JLabel();
        lblNewEmployeeName = new javax.swing.JLabel();
        lblNewEmployeeEmail = new javax.swing.JLabel();
        lblNewEmployeePhoneNumber = new javax.swing.JLabel();
        lblNewEmployeeUsername = new javax.swing.JLabel();
        lblNewEmployeeSecurityLevel = new javax.swing.JLabel();
        lblNewEmployeePassword = new javax.swing.JLabel();
        newEmployeeID = new javax.swing.JTextField();
        newEmployeeTitle = new javax.swing.JTextField();
        newEmployeeName = new javax.swing.JTextField();
        newEmployeeEmail = new javax.swing.JTextField();
        newEmployeePhoneNumber = new javax.swing.JTextField();
        newEmployeeUsername = new javax.swing.JTextField();
        newEmployeeSecurityLevel = new javax.swing.JTextField();
        newEmployeePassword = new javax.swing.JTextField();
        btnAddEmployee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnClearEmployeeInterface = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuNewEmployee = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNewEmployeeID.setText("New Employee ID: ");

        lblNewEmployeeTitle.setText("New Employee Title:");

        lblNewEmployeeName.setText("New Employee Name:");

        lblNewEmployeeEmail.setText("New Employee Email:");

        lblNewEmployeePhoneNumber.setText("New Employee Phone Number:");

        lblNewEmployeeUsername.setText("New Employee Username:");

        lblNewEmployeeSecurityLevel.setText("New Employee Security Level:");

        lblNewEmployeePassword.setText("New Employee Password:");

        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Employee");

        btnClearEmployeeInterface.setText("Clear");
        btnClearEmployeeInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEmployeeInterfaceActionPerformed(evt);
            }
        });

        jmnuNewEmployee.setText("View");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Main Admin Interface");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnuNewEmployee.add(jMenuItem1);

        jMenuBar1.add(jmnuNewEmployee);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearEmployeeInterface)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNewEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeePhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeeUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeeSecurityLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewEmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newEmployeeID)
                                    .addComponent(newEmployeeTitle)
                                    .addComponent(newEmployeeName)
                                    .addComponent(newEmployeeEmail)
                                    .addComponent(newEmployeePhoneNumber)
                                    .addComponent(newEmployeeUsername)
                                    .addComponent(newEmployeeSecurityLevel)
                                    .addComponent(newEmployeePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeID)
                    .addComponent(newEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeTitle)
                    .addComponent(newEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeName)
                    .addComponent(newEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeEmail)
                    .addComponent(newEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeePhoneNumber)
                    .addComponent(newEmployeePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeUsername)
                    .addComponent(newEmployeeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeeSecurityLevel)
                    .addComponent(newEmployeeSecurityLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployeePassword)
                    .addComponent(newEmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmployee)
                    .addComponent(btnClearEmployeeInterface))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
       String newEmpEmail = newEmployeeEmail.getText();
       Database.companyDatabase.generateNewEmployeeID();
       newEmployeeID.setText(Integer.toString(Database.companyDatabase.getNewEmployeeID()));
       String idPassVariable = newEmployeeID.getText();
       int newEmpID = Integer.parseInt(idPassVariable);
       String newEmpName = newEmployeeName.getText();
       String newEmpPhoneNumber = newEmployeePhoneNumber.getText();
       String newEmpPassword = Database.companyDatabase.encrypt(newEmployeePassword.getText());
       String securityLevelPassVariable = newEmployeeSecurityLevel.getText();
       int newEmpSecurityLevel = Integer.parseInt(securityLevelPassVariable);
       String newEmpTitle = newEmployeeTitle.getText();
       String newEmpUsername = newEmployeeUsername.getText();
    
       Database.companyDatabase.employees.add(new Employee(newEmpID, newEmpTitle, newEmpName, newEmpEmail, newEmpPhoneNumber, newEmpUsername, newEmpSecurityLevel, newEmpPassword));
    
    
    
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnClearEmployeeInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEmployeeInterfaceActionPerformed
        newEmployeeEmail.setText("");
        newEmployeeID.setText("");
        newEmployeeName.setText("");
        newEmployeePhoneNumber.setText("");
        newEmployeePassword.setText("");
        newEmployeeSecurityLevel.setText("");
        newEmployeeTitle.setText("");
        newEmployeeUsername.setText("");
    }//GEN-LAST:event_btnClearEmployeeInterfaceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new AdminInterface().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnClearEmployeeInterface;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmnuNewEmployee;
    private javax.swing.JLabel lblNewEmployeeEmail;
    private javax.swing.JLabel lblNewEmployeeID;
    private javax.swing.JLabel lblNewEmployeeName;
    private javax.swing.JLabel lblNewEmployeePassword;
    private javax.swing.JLabel lblNewEmployeePhoneNumber;
    private javax.swing.JLabel lblNewEmployeeSecurityLevel;
    private javax.swing.JLabel lblNewEmployeeTitle;
    private javax.swing.JLabel lblNewEmployeeUsername;
    private javax.swing.JTextField newEmployeeEmail;
    private javax.swing.JTextField newEmployeeID;
    private javax.swing.JTextField newEmployeeName;
    private javax.swing.JTextField newEmployeePassword;
    private javax.swing.JTextField newEmployeePhoneNumber;
    private javax.swing.JTextField newEmployeeSecurityLevel;
    private javax.swing.JTextField newEmployeeTitle;
    private javax.swing.JTextField newEmployeeUsername;
    // End of variables declaration//GEN-END:variables
}
