/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bermudatechsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Nathan Cabral
 */
public class OrderProduct extends javax.swing.JFrame {

    /**
     * Creates new form OrderProduct
     */
    public OrderProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrderProducts = new javax.swing.JLabel();
        productNameToBeOrdered = new javax.swing.JTextField();
        hardwareTypeToBeOrdered = new javax.swing.JTextField();
        productPriceToBeOrdered = new javax.swing.JTextField();
        currentProductQuantityToBeOrdered = new javax.swing.JTextField();
        lblproductIDToBeOrdered = new javax.swing.JLabel();
        addedSupplierID = new javax.swing.JTextField();
        lblProductNameToBeOrdered = new javax.swing.JLabel();
        btnImportInformation = new javax.swing.JButton();
        lblHardwareTypeToBeOrdered = new javax.swing.JLabel();
        lblProductPriceToBeOrdered = new javax.swing.JLabel();
        lblCurrentProductQuantityToBeOrdered = new javax.swing.JLabel();
        lblSupplierIDToBeOrdered = new javax.swing.JLabel();
        productIDToBeOrdered = new javax.swing.JTextField();
        lblProductInformation = new javax.swing.JLabel();
        supplierRepresentativeEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        suppliedProducts = new javax.swing.JTextField();
        lblSupplierName = new javax.swing.JLabel();
        lblSupplierRepresentativeName = new javax.swing.JLabel();
        lblSupplierRepresentativeNumber = new javax.swing.JLabel();
        lblSupplierRepresentativeEmail = new javax.swing.JLabel();
        supplierName = new javax.swing.JTextField();
        lblSuppliedProducts = new javax.swing.JLabel();
        supplierRepresentativeName = new javax.swing.JTextField();
        supplierID = new javax.swing.JTextField();
        supplierRepresentativeNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblOrderInformation = new javax.swing.JLabel();
        lblQuantityToBeOrdered = new javax.swing.JLabel();
        lblPurchaseOrderNumber = new javax.swing.JLabel();
        quantityToBeOrdered = new javax.swing.JTextField();
        purchaseOrderNumber = new javax.swing.JTextField();
        btnOrderProduct = new javax.swing.JButton();
        btnClearOrderForm = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        adminInterface = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOrderProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrderProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderProducts.setText("Order Products");

        productPriceToBeOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceToBeOrderedActionPerformed(evt);
            }
        });

        lblproductIDToBeOrdered.setText("Product ID:");

        lblProductNameToBeOrdered.setText("Product Name: ");

        btnImportInformation.setText("Import Information");
        btnImportInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportInformationActionPerformed(evt);
            }
        });

        lblHardwareTypeToBeOrdered.setText("Hardware Type:");

        lblProductPriceToBeOrdered.setText("Product Price:");

        lblCurrentProductQuantityToBeOrdered.setText("Current Product Quantity:");

        lblSupplierIDToBeOrdered.setText("Supplier ID:");

        productIDToBeOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDToBeOrderedActionPerformed(evt);
            }
        });

        lblProductInformation.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblProductInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductInformation.setText("Product Information");

        jLabel8.setText("Supplier ID:");

        lblSupplierName.setText("Supplier Name:");

        lblSupplierRepresentativeName.setText("Supplier Representative Name: ");

        lblSupplierRepresentativeNumber.setText("Supplier Representative Number:");

        lblSupplierRepresentativeEmail.setText("Supplier Representative Email:");

        lblSuppliedProducts.setText("Supplied Products:");

        supplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierIDActionPerformed(evt);
            }
        });

        supplierRepresentativeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierRepresentativeNumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Information");

        lblOrderInformation.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblOrderInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderInformation.setText("Order Information");

        lblQuantityToBeOrdered.setText("Quantity To Be Ordered:");

        lblPurchaseOrderNumber.setText("Purchase Order Number:");

        quantityToBeOrdered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityToBeOrderedActionPerformed(evt);
            }
        });

        btnOrderProduct.setText("Order Product");
        btnOrderProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderProductActionPerformed(evt);
            }
        });

        btnClearOrderForm.setText("Clear Order");
        btnClearOrderForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderFormActionPerformed(evt);
            }
        });

        jMenu1.setText("View");

        adminInterface.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        adminInterface.setText("Admin Interface");
        adminInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInterfaceActionPerformed(evt);
            }
        });
        jMenu1.add(adminInterface);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProductInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblproductIDToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProductNameToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblHardwareTypeToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProductPriceToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierIDToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCurrentProductQuantityToBeOrdered, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameToBeOrdered)
                                    .addComponent(hardwareTypeToBeOrdered)
                                    .addComponent(productPriceToBeOrdered)
                                    .addComponent(currentProductQuantityToBeOrdered)
                                    .addComponent(addedSupplierID)
                                    .addComponent(productIDToBeOrdered)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierRepresentativeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierRepresentativeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSuppliedProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierRepresentativeEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addComponent(supplierRepresentativeName)
                                    .addComponent(supplierRepresentativeNumber)
                                    .addComponent(supplierRepresentativeEmail)
                                    .addComponent(suppliedProducts)
                                    .addComponent(supplierID)))
                            .addComponent(btnImportInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQuantityToBeOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPurchaseOrderNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseOrderNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(quantityToBeOrdered))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOrderInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnClearOrderForm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOrderProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductInformation)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblproductIDToBeOrdered)
                            .addComponent(productIDToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductNameToBeOrdered)
                            .addComponent(productNameToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHardwareTypeToBeOrdered)
                            .addComponent(hardwareTypeToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductPriceToBeOrdered)
                            .addComponent(productPriceToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurrentProductQuantityToBeOrdered)
                            .addComponent(currentProductQuantityToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierIDToBeOrdered)
                            .addComponent(addedSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(supplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplierName)
                            .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplierRepresentativeName)
                            .addComponent(supplierRepresentativeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrderInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantityToBeOrdered)
                            .addComponent(quantityToBeOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPurchaseOrderNumber)
                            .addComponent(purchaseOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrderProduct)
                            .addComponent(btnClearOrderForm))
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierRepresentativeNumber)
                    .addComponent(supplierRepresentativeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierRepresentativeEmail)
                    .addComponent(supplierRepresentativeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSuppliedProducts)
                    .addComponent(suppliedProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnImportInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productPriceToBeOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceToBeOrderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceToBeOrderedActionPerformed

    private void btnImportInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportInformationActionPerformed
        getProductToBeOrdered();
    }//GEN-LAST:event_btnImportInformationActionPerformed

    private void productIDToBeOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDToBeOrderedActionPerformed
        getProductToBeOrdered();
    }//GEN-LAST:event_productIDToBeOrderedActionPerformed

    private void supplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIDActionPerformed

    private void supplierRepresentativeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierRepresentativeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierRepresentativeNumberActionPerformed

    private void quantityToBeOrderedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityToBeOrderedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityToBeOrderedActionPerformed

    private void btnOrderProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderProductActionPerformed
       int confirmResponse = JOptionPane.showConfirmDialog(this,"Do you want to confirm this order?", "Confirm Order", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       
       if(confirmResponse == JOptionPane.YES_OPTION)
       {
            String amountOrdered = quantityToBeOrdered.getText();
            String purchaseOrder = purchaseOrderNumber.getText();
            
            String displayMessage = ( amountOrdered +" "+ stockingProductName + " have been Ordered \n" + "Purchase Order Number for this order is: " + purchaseOrder );
            
            JOptionPane.showMessageDialog(null, displayMessage, " Product Ordered ", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Order Has Not Been Placed", "Order Cancelled", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_btnOrderProductActionPerformed

    private void adminInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInterfaceActionPerformed
        this.setVisible(false);
        new AdminInterface().setVisible(true);
    }//GEN-LAST:event_adminInterfaceActionPerformed

    private void btnClearOrderFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderFormActionPerformed
    productIDToBeOrdered.setText("");
    productNameToBeOrdered.setText("");
    productPriceToBeOrdered.setText("");
    purchaseOrderNumber.setText("");
    quantityToBeOrdered.setText("");
    suppliedProducts.setText("");
    supplierID.setText("");
    supplierName.setText("");
    supplierRepresentativeEmail.setText("");
    supplierRepresentativeName.setText("");
    supplierRepresentativeNumber.setText("");
    currentProductQuantityToBeOrdered.setText("");
    hardwareTypeToBeOrdered.setText("");
    addedSupplierID.setText("");
    }//GEN-LAST:event_btnClearOrderFormActionPerformed
    public void getProductToBeOrdered()
    {
        String stockingProductID;
        stockingProductID = productIDToBeOrdered.getText();
         
         for(Product e : Database.companyDatabase.products)
         {
             if(stockingProductID.equalsIgnoreCase(e.getProductID()))
             {
                 String stockingHardwareType = e.getHardwareType();
                 stockingProductName = e.getProductName();
                 String stockingProductPrice = Integer.toString(e.getPrice());
                 String stockingCurrentProductQuantity = Integer.toString(e.getQuantity());
                 stockingSupplierID = e.getSupplier();
                 
                 hardwareTypeToBeOrdered.setText(stockingHardwareType);
                 productNameToBeOrdered.setText(stockingProductName);
                 productPriceToBeOrdered.setText(stockingProductPrice);
                 currentProductQuantityToBeOrdered.setText(stockingCurrentProductQuantity);
                 addedSupplierID.setText(stockingSupplierID);
              }
         }
         for(Supplier f: Database.companyDatabase.suppliers)
         {
             if(stockingSupplierID.equalsIgnoreCase(f.getSupplierID()))
             {
                 String writingSupplierName = f.getSupplierName();
                 String writingSupplierRepresentativeName = f.getRepresentativeName();
                 String writingSupplierRepresentativeNumber = f.getRepresentativeNumber();
                 String writingSupplierRepresentativeEmail = f.getRepresentativeEmail();
                 String writingSuppliedProducts = f.getSuppliedProduct();
                 
                 supplierID.setText(stockingSupplierID);
                 supplierName.setText(writingSupplierName);
                 supplierRepresentativeName.setText(writingSupplierRepresentativeName);
                 supplierRepresentativeNumber.setText(writingSupplierRepresentativeNumber);
                 supplierRepresentativeEmail.setText(writingSupplierRepresentativeEmail);
                 suppliedProducts.setText(writingSuppliedProducts);
             }
         }
    }        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderProduct().setVisible(true);
            }
        });
    }
    
    String stockingSupplierID; 
    String stockingProductName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addedSupplierID;
    private javax.swing.JMenuItem adminInterface;
    private javax.swing.JButton btnClearOrderForm;
    private javax.swing.JButton btnImportInformation;
    private javax.swing.JButton btnOrderProduct;
    private javax.swing.JTextField currentProductQuantityToBeOrdered;
    private javax.swing.JTextField hardwareTypeToBeOrdered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCurrentProductQuantityToBeOrdered;
    private javax.swing.JLabel lblHardwareTypeToBeOrdered;
    private javax.swing.JLabel lblOrderInformation;
    private javax.swing.JLabel lblOrderProducts;
    private javax.swing.JLabel lblProductInformation;
    private javax.swing.JLabel lblProductNameToBeOrdered;
    private javax.swing.JLabel lblProductPriceToBeOrdered;
    private javax.swing.JLabel lblPurchaseOrderNumber;
    private javax.swing.JLabel lblQuantityToBeOrdered;
    private javax.swing.JLabel lblSuppliedProducts;
    private javax.swing.JLabel lblSupplierIDToBeOrdered;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblSupplierRepresentativeEmail;
    private javax.swing.JLabel lblSupplierRepresentativeName;
    private javax.swing.JLabel lblSupplierRepresentativeNumber;
    private javax.swing.JLabel lblproductIDToBeOrdered;
    private javax.swing.JTextField productIDToBeOrdered;
    private javax.swing.JTextField productNameToBeOrdered;
    private javax.swing.JTextField productPriceToBeOrdered;
    private javax.swing.JTextField purchaseOrderNumber;
    private javax.swing.JTextField quantityToBeOrdered;
    private javax.swing.JTextField suppliedProducts;
    private javax.swing.JTextField supplierID;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierRepresentativeEmail;
    private javax.swing.JTextField supplierRepresentativeName;
    private javax.swing.JTextField supplierRepresentativeNumber;
    // End of variables declaration//GEN-END:variables
}
